//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integral.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Integral.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] btn_close {
            get {
                object obj = ResourceManager.GetObject("btn_close", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] btn_maximize {
            get {
                object obj = ResourceManager.GetObject("btn_maximize", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] btn_minimize {
            get {
                object obj = ResourceManager.GetObject("btn_minimize", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Button_Common_Create {
            get {
                return ResourceManager.GetString("Button_Common_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Common_Delete {
            get {
                return ResourceManager.GetString("Button_Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Button_Common_Logout {
            get {
                return ResourceManager.GetString("Button_Common_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Button_Common_Menu {
            get {
                return ResourceManager.GetString("Button_Common_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Button_Common_Refresh {
            get {
                return ResourceManager.GetString("Button_Common_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Button_Common_SaveChanges {
            get {
                return ResourceManager.GetString("Button_Common_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/Export Data.
        /// </summary>
        public static string Button_DataManagement_ImportExportData {
            get {
                return ResourceManager.GetString("Button_DataManagement_ImportExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load/Extract Data.
        /// </summary>
        public static string Button_DataManagement_LoadExtractData {
            get {
                return ResourceManager.GetString("Button_DataManagement_LoadExtractData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Leader.
        /// </summary>
        public static string Button_Group_ChangeLeader {
            get {
                return ResourceManager.GetString("Button_Group_ChangeLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Students.
        /// </summary>
        public static string Button_Group_ModifyStudents {
            get {
                return ResourceManager.GetString("Button_Group_ModifyStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Search.
        /// </summary>
        public static string Button_Meetings_ClearSearch {
            get {
                return ResourceManager.GetString("Button_Meetings_ClearSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Session_AddAddress {
            get {
                return ResourceManager.GetString("Button_Session_AddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Button_Session_Login {
            get {
                return ResourceManager.GetString("Button_Session_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Users_AddRole {
            get {
                return ResourceManager.GetString("Button_Users_AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Button_Users_RemoveRole {
            get {
                return ResourceManager.GetString("Button_Users_RemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;101&quot;:&quot;Incorrect Password.&quot;,
        /// &quot;102&quot;:&quot;User Does Not Exist.&quot;,
        /// &quot;103&quot;:&quot;User Does Not Have That Role.&quot;,
        /// &quot;201&quot;:&quot;User With That Id Does Not Exist.&quot;,
        /// &quot;202&quot;:&quot;User With That Username Already Exists.&quot;,
        /// &quot;203&quot;:&quot;That User Already Has That Role.&quot;,
        /// &quot;204&quot;:&quot;That User Does Not Have Any Roles.&quot;,
        /// &quot;205&quot;:&quot;That User Does Not Have That Role.&quot;,
        /// &quot;206&quot;:&quot;That User Has Groups.&quot;,
        /// &quot;301&quot;:&quot;Student With That Id Does Not Exist&quot;,
        /// &quot;401&quot;:&quot;Group With That Id Does Not Exist&quot;,
        /// &quot;402&quot;:&quot;Group With That Combination Of Grade And [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ErrorStrings {
            get {
                return ResourceManager.GetString("ErrorStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] integral_icon {
            get {
                object obj = ResourceManager.GetObject("integral_icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] integral_icon_image {
            get {
                object obj = ResourceManager.GetObject("integral_icon_image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Common_Password {
            get {
                return ResourceManager.GetString("Label_Common_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Label_Common_Username {
            get {
                return ResourceManager.GetString("Label_Common_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Label_DataManagement_Path {
            get {
                return ResourceManager.GetString("Label_DataManagement_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Label_Group_Grade {
            get {
                return ResourceManager.GetString("Label_Group_Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group`s Students.
        /// </summary>
        public static string Label_Group_GroupStudents {
            get {
                return ResourceManager.GetString("Label_Group_GroupStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Type.
        /// </summary>
        public static string Label_Group_GroupType {
            get {
                return ResourceManager.GetString("Label_Group_GroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        public static string Label_Group_Leader {
            get {
                return ResourceManager.GetString("Label_Group_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_Group_Name {
            get {
                return ResourceManager.GetString("Label_Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Label_Meetings_Date {
            get {
                return ResourceManager.GetString("Label_Meetings_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group`s Meetings.
        /// </summary>
        public static string Label_Meetings_GroupsMeetings {
            get {
                return ResourceManager.GetString("Label_Meetings_GroupsMeetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Label_Meetings_Note {
            get {
                return ResourceManager.GetString("Label_Meetings_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Label_Meetings_Theme {
            get {
                return ResourceManager.GetString("Label_Meetings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Label_Session_Address {
            get {
                return ResourceManager.GetString("Label_Session_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_Session_Name {
            get {
                return ResourceManager.GetString("Label_Session_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Label_Session_Role {
            get {
                return ResourceManager.GetString("Label_Session_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address.
        /// </summary>
        public static string Label_Session_ServerAddress {
            get {
                return ResourceManager.GetString("Label_Session_ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Label_Students_FirstName {
            get {
                return ResourceManager.GetString("Label_Students_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student`s Groups.
        /// </summary>
        public static string Label_Students_Groups {
            get {
                return ResourceManager.GetString("Label_Students_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        public static string Label_Students_SecondName {
            get {
                return ResourceManager.GetString("Label_Students_SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Name.
        /// </summary>
        public static string Label_Students_ThirdName {
            get {
                return ResourceManager.GetString("Label_Students_ThirdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non User`s Roles:.
        /// </summary>
        public static string Label_Users_NonUserRoles {
            get {
                return ResourceManager.GetString("Label_Users_NonUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User`s Roles:.
        /// </summary>
        public static string Label_Users_UserRoles {
            get {
                return ResourceManager.GetString("Label_Users_UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ModalButton_Cancel {
            get {
                return ResourceManager.GetString("ModalButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ModalButton_Ok {
            get {
                return ResourceManager.GetString("ModalButton_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string ModalHeader_DataManagement_SelectFile {
            get {
                return ResourceManager.GetString("ModalHeader_DataManagement_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Leader.
        /// </summary>
        public static string ModalHeader_Groups_ChangeLeader {
            get {
                return ResourceManager.GetString("ModalHeader_Groups_ChangeLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string ModalHeader_Groups_CreateGroup {
            get {
                return ResourceManager.GetString("ModalHeader_Groups_CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Students.
        /// </summary>
        public static string ModalHeader_Groups_ModifyStudents {
            get {
                return ResourceManager.GetString("ModalHeader_Groups_ModifyStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Meeting.
        /// </summary>
        public static string ModalHeader_Meetings_CreateMeeting {
            get {
                return ResourceManager.GetString("ModalHeader_Meetings_CreateMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        public static string ModalHeader_Session_AddAddress {
            get {
                return ResourceManager.GetString("ModalHeader_Session_AddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ModalHeader_Session_Login {
            get {
                return ResourceManager.GetString("ModalHeader_Session_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Address.
        /// </summary>
        public static string ModalHeader_Session_SelectAddressDialog {
            get {
                return ResourceManager.GetString("ModalHeader_Session_SelectAddressDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Student.
        /// </summary>
        public static string ModalHeader_Students_CreateStudent {
            get {
                return ResourceManager.GetString("ModalHeader_Students_CreateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string ModalHeader_Users_CreateUser {
            get {
                return ResourceManager.GetString("ModalHeader_Users_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Management.
        /// </summary>
        public static string RadioButton_Navigation_DataManagement {
            get {
                return ResourceManager.GetString("RadioButton_Navigation_DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string RadioButton_Navigation_Groups {
            get {
                return ResourceManager.GetString("RadioButton_Navigation_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetings.
        /// </summary>
        public static string RadioButton_Navigation_Meetings {
            get {
                return ResourceManager.GetString("RadioButton_Navigation_Meetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string RadioButton_Navigation_Students {
            get {
                return ResourceManager.GetString("RadioButton_Navigation_Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string RadioButton_Navigation_Users {
            get {
                return ResourceManager.GetString("RadioButton_Navigation_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorStrings_US.txt.
        /// </summary>
        public static string Resources_ErrorStringsDictionary_Name {
            get {
                return ResourceManager.GetString("Resources_ErrorStringsDictionary_Name", resourceCulture);
            }
        }
    }
}
